# Generated by Django 4.1.4 on 2022-12-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='address',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='comment',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='positions',
            field=models.ManyToManyField(to='api.posithionforshopingcart'),
        ),
    ]
