# Generated by Django 4.1.4 on 2022-12-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='По возвростанию', verbose_name='Очередность отображения'),
        ),
    ]
