# Generated by Django 4.1.4 on 2022-12-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_position_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
