# Generated by Django 4.1.4 on 2022-12-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_order_alter_shoppingcart_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='positions',
            new_name='positions_in_cart',
        ),
    ]
