# Generated by Django 4.1.4 on 2022-12-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ingredient_position_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
    ]
