# Generated by Django 4.1.4 on 2022-12-14 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=123, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IngredientsInPosition',
        ),
    ]
