# Generated by Django 4.1.4 on 2022-12-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ingredient_amount_delete_ingredientsinposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='image',
        ),
        migrations.CreateModel(
            name='ImagePositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='None')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position')),
            ],
        ),
    ]
