# Generated by Django 4.1.4 on 2022-12-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_position_image_imagepositions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepositions',
            old_name='images',
            new_name='image',
        ),
    ]
