# Generated by Django 4.1.4 on 2022-12-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_images_imagepositions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepositions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
