# Generated by Django 4.1.4 on 2022-12-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_imagepositions_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepositions',
            name='position',
        ),
        migrations.AddField(
            model_name='position',
            name='images',
            field=models.ManyToManyField(related_name='positions', to='api.imagepositions'),
        ),
    ]
