# Generated by Django 4.1.4 on 2022-12-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('comment', models.CharField(max_length=1024, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Позвоните мне',
                'verbose_name_plural': 'Позвоните мне',
            },
        ),
    ]
