# Generated by Django 4.1.4 on 2022-12-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_contact_address_alter_contact_address_on_map_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='links',
            field=models.ManyToManyField(to='users.link'),
        ),
    ]
